services:
  image-splitter:
    image: image-splitter:amd64
    container_name: image-splitter
    ports:
      - "8001:8001"
    volumes:
      - /vol1/1000/services/data/image-splitter:/app/data
      - /vol1/1000/services/data/image-splitter-cache/u2net:/root/.u2net
      - /vol1/1000/services/data/image-splitter-cache/huggingface:/root/.cache/huggingface
      - /vol1/1000/services/data/image-splitter-cache/realesrgan:/app/backend/app/upscalers/weights
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
